### ISSUE TITLE
Exibir thumbnails dos vídeos do YouTube.

### ISSUE THREAD

**Issue by ravishi** [labhackercd/edm#14]
Com um intent associado para a execução do vídeo.

**Comment by gbrego** [comment]
A funcionalidade está pronta, contudo ainda não consegui fazer o overlay preto por cima da imagem. O botão ficou o branco mesmo. O problema aqui é quando temos um thumbnail muito claro, fica díficil de ver o botão de player.


Alguma sugestão de implementação?

**Comment by ravishi** [comment]
Cara, vou tentar fazer um overlay pra escurecer um pouco o thumbnail. Mas mesmo assim, isso vai voltar pro backlog, pois precisamos fechar essa milestone até o dia 26.

**Comment by ravishi** [comment]
Solved by #7 at 3980773c8613eecf4d394dec8e85b348f7ae52d1.
